Added size unit for Content size and File size filters
Alfresco/alfresco-mobile-workspace-ios pull request #430
Opened 2022-01-24 10:26 UTC by ankitgoyalgloballogic

#REF: #MOBILEAPPS-1041

2022-01-25 11:59 UTC, aman-alfresco commented on ContentApp/Modules/Advance Search/Number Range/SearchNumberRangeComponentViewModel.swift
> +        return String(format: "%@ (KB)", name)
please define in the string file for localization

2022-01-25 12:44 UTC, ankitgoyalgloballogic commented on ContentApp/Modules/Advance Search/Number Range/SearchNumberRangeComponentViewModel.swift
> +        return String(format: "%@ (KB)", name)
Done

2022-01-27 05:17 UTC, gl-lovekesh requested changes

2022-01-27 05:17 UTC, gl-lovekesh commented on ContentApp/BusinessLayer/Lists/Models/SearchFacetFields.swift
> +        let fileSizeLocalizedString = NSLocalizedString("SEARCH.FACET_FIELDS.SIZE", comment: "")
Need to compare the key not value for the key.

2022-01-27 05:17 UTC, gl-lovekesh commented on ContentApp/Modules/Advance Search/List with Search/SearchFacetListComponentViewModel.swift
> +    func isFileSizeFacet(for label: String?) -> Bool {
Reuse it as used before as used.

2022-01-27 07:53 UTC, aman-alfresco approved these changes

2022-01-27 08:19 UTC, merged