Mobileapps 1078
Alfresco/alfresco-mobile-workspace-ios pull request #437
Opened 2022-02-25 16:54 UTC by ankitgoyalgloballogic

1. Database Migration
2. Allow user to search within app extension

2022-02-26 14:20 UTC, aman-alfresco commented on Share/ListComponent/SystemSearchViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 0.01) { [weak self] in
Do we add some delay like 0.01?

2022-02-26 14:20 UTC, aman-alfresco approved these changes

2022-02-28 05:32 UTC, gl-lovekesh requested changes

2022-02-28 05:32 UTC, gl-lovekesh commented on ContentApp/PersistenceLayer/Services/DatabaseMigrationService.swift
> +        if !downloadedNodes.isEmpty {
make a common function pass the nodes only.
func migrateNodes(nodes : ListNodes){
for node in downloadedNodes {
                let nodeToBeStored = node
                if node.id != 0 {
                    nodeToBeStored.id = 0
                }
                databaseService?.store(entity: nodeToBeStored)
                self.remove(entity: node)
            }
        }
}

2022-02-28 06:03 UTC, ankitgoyalgloballogic commented on ContentApp/PersistenceLayer/Services/DatabaseMigrationService.swift
> +        if !downloadedNodes.isEmpty {
Done

2022-02-28 06:12 UTC, gl-lovekesh approved these changes

2022-02-28 06:12 UTC, gl-lovekesh commented on Share/ListComponent/SystemSearchViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 0.01) { [weak self] in
that is required for screen animation to be completed .

2022-02-28 06:12 UTC, merged