Mobileapps 1143
Alfresco/alfresco-mobile-workspace-ios pull request #455
Opened 2022-05-06 09:00 UTC by ankitgoyalgloballogic

2022-05-06 13:01 UTC, aman-alfresco submitted a review, later dismissed

2022-05-09 05:24 UTC, gl-lovekesh requested changes

2022-05-09 05:24 UTC, gl-lovekesh commented on ContentApp/BusinessLayer/Action Menu/ViewModels/NodeActionsViewModel.swift
> +    var moveDelegate: NodeActionMoveDelegate?
make it weak.

2022-05-09 05:24 UTC, gl-lovekesh commented on ContentApp/BusinessLayer/Lists/Models/OfflineFolderDrillModel.swift
> +        case .moveToFolder:
Merge the same cases.

2022-05-09 05:24 UTC, gl-lovekesh commented on ContentApp/PresentationLayer/Components/SystemSearch+ListActions.swift
> +extension SystemSearchViewController: NodeActionsViewModelDelegate,
Clean this file, Remove unwanted code.

2022-05-09 06:29 UTC, ankitgoyalgloballogic commented on ContentApp/BusinessLayer/Action Menu/ViewModels/NodeActionsViewModel.swift
> +    var moveDelegate: NodeActionMoveDelegate?
Done

2022-05-09 06:32 UTC, ankitgoyalgloballogic commented on ContentApp/BusinessLayer/Lists/Models/OfflineFolderDrillModel.swift
> +        case .moveToFolder:
Done

2022-05-09 06:34 UTC, ankitgoyalgloballogic commented on ContentApp/PresentationLayer/Components/SystemSearch+ListActions.swift
> +extension SystemSearchViewController: NodeActionsViewModelDelegate,
Done

2022-05-09 07:10 UTC, gl-lovekesh approved these changes

2022-05-09 07:11 UTC, merged