Navigate user to the created folder
Alfresco/alfresco-mobile-workspace-ios pull request #463
Opened 2022-05-12 14:10 UTC by ankitgoyalgloballogic

#REF: #MOBILEAPPS-1174

2022-05-13 12:48 UTC, gl-lovekesh commented on ContentApp/PresentationLayer/Components/ListComponent/ListComponentViewController.swift
> +        let isMove = appDelegate()?.isMoveFilesAndFolderFlow ?? false
Remove the check for isMove. Make it constant for both flows.

2022-05-13 12:48 UTC, gl-lovekesh approved these changes

2022-05-13 12:50 UTC, gl-lovekesh requested changes
please remove all isMove checks.

2022-05-14 04:54 UTC, ankitgoyalgloballogic commented on ContentApp/PresentationLayer/Components/ListComponent/ListComponentViewController.swift
> +        let isMove = appDelegate()?.isMoveFilesAndFolderFlow ?? false
Done

2022-05-14 04:55 UTC, ankitgoyalgloballogic commented
Navigate to the folder after create

2022-05-14 04:55 UTC, merged