upload task attachment UI
Alfresco/alfresco-mobile-workspace-ios pull request #532
Opened 2022-10-11 07:37 UTC by ankitgoyalgloballogic

#REF: #MOBILEAPPS-1438

2022-10-12 10:49 UTC, gl-lovekesh requested changes

2022-10-12 10:49 UTC, gl-lovekesh commented on ContentApp/PresentationLayer/Tasks/Task List/Controller/Task Detail/TaskDetailViewController.swift
> +    private func handleAction(action: ActionMenu) {
Why do we require this method as it's doing debug logs only?

2022-10-12 11:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Alfresco/alfresco-mobile-workspace-ios?pullRequest=532) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Alfresco/alfresco-mobile-workspace-ios?pullRequest=532) before we can accept your contribution.<br/><hr/>**Ankit Goyal** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Alfresco/alfresco-mobile-workspace-ios?pullRequest=532) it.</sub>

2022-10-13 06:02 UTC, ankitgoyalgloballogic commented on ContentApp/PresentationLayer/Tasks/Task List/Controller/Task Detail/TaskDetailViewController.swift
> +    private func handleAction(action: ActionMenu) {
This was under development code. I have already removed it.

2022-10-14 11:07 UTC, gl-lovekesh approved these changes

2022-10-14 11:09 UTC, merged