ADST-484
Alfresco/alfresco-mobile-workspace-ios pull request #674
Opened 2024-07-08 10:36 UTC by PiplaniVinay

2024-07-09 04:53 UTC, aman-alfresco requested changes

2024-07-09 04:53 UTC, aman-alfresco commented on ContentApp/BusinessLayer/Authentication/Models/AuthenticationParameters.swift
> +    var authTypeID: String = "1"
Please use pkce, oidc for unique IDs instead of numbers

2024-07-09 04:53 UTC, aman-alfresco commented on ContentApp/BusinessLayer/Localization/en.lproj/Localizable.strings
> +"keyClock" = "KeyClock";
It's keycloak. Please correct the spelling

2024-07-09 04:53 UTC, aman-alfresco commented on ContentApp/PresentationLayer/Authentication/Screens/AdvancedSettingsViewController.swift
> +            createTaskOptionItem(id: "1", name: LocalizationConstants.Labels.keyClock),
Use Authtype in IDs

2024-07-09 04:53 UTC, aman-alfresco commented on ContentApp/PresentationLayer/Authentication/Screens/AdvancedSettingsViewController.swift
> +        transportProtocolLabel.isHidden = isHidden
Can we make the parent view hide instead of hiding all view?

2024-07-09 13:44 UTC, PiplaniVinay commented on ContentApp/BusinessLayer/Authentication/Models/AuthenticationParameters.swift
> +    var authTypeID: String = "1"
Done

2024-07-09 13:44 UTC, PiplaniVinay commented on ContentApp/BusinessLayer/Localization/en.lproj/Localizable.strings
> +"keyClock" = "KeyClock";
Done

2024-07-09 13:44 UTC, PiplaniVinay commented on ContentApp/PresentationLayer/Authentication/Screens/AdvancedSettingsViewController.swift
> +            createTaskOptionItem(id: "1", name: LocalizationConstants.Labels.keyClock),
Done

2024-07-09 13:48 UTC, PiplaniVinay commented on ContentApp/PresentationLayer/Authentication/Screens/AdvancedSettingsViewController.swift
> +        transportProtocolLabel.isHidden = isHidden
Hiding the parent view can be challenging on small devices, so I've hidden the labels and fields instead.

2024-07-09 14:10 UTC, aman-alfresco approved these changes

2024-07-10 04:38 UTC, gl-lovekesh approved these changes

2024-07-10 04:41 UTC, gl-lovekesh commented
Creating a separate branch to Support OIDC changes.

2024-07-10 04:41 UTC, closed without merging