ADST-569
Alfresco/alfresco-mobile-workspace-ios pull request #679
Opened 2024-08-22 05:56 UTC by PiplaniVinay

2024-08-28 05:44 UTC, gl-lovekesh reviewed
Please add description for this PR

2024-09-13 07:22 UTC, gl-lovekesh requested changes

2024-09-13 07:22 UTC, gl-lovekesh commented on ContentApp/BusinessLayer/Authentication/ViewModels/ConnectViewModel.swift
>                  switch authType {
Remove this unused code,

2024-09-16 06:48 UTC, PiplaniVinay commented on ContentApp/BusinessLayer/Authentication/ViewModels/ConnectViewModel.swift
>                  switch authType {
Done

2024-09-16 07:00 UTC, aman-alfresco approved these changes

2024-09-16 08:22 UTC, gl-lovekesh approved these changes

2024-09-16 08:23 UTC, merged